Update sman

diff --git a/binaries/bin/sman b/binaries/bin/sman
--- a/binaries/bin/sman
+++ b/binaries/bin/sman
@@ -78,7 +78,14 @@ __sd_directory_help() {
             max_length=$((length > max_length ? length : max_length))
         done
 
-    # zsh doesn't support ${!commands[@]} expansion
+    if [[ -n ${ZSH_EVAL_CONTEXT+x} ]]; then
+      set -o LOCAL_OPTIONS
+      # we need to ensure we have 0-indexed arrays
+      # in order for this loop to work properly.                                       
+      # zsh doesn't support ${!commands[@]} expansion
+      set -o KSH_ARRAYS
+    fi
+    
     for ((i = 0; i < ${#commands[@]}; i++)); do
         printf "%-${max_length}s -- %s\n" "${commands[i]}" "${helps[i]}"
     done
@@ -103,8 +110,25 @@ __sd_help() {
     fi
 }
 
+__sd_print_template() {
+    if [[ -f "$1/template" ]]; then
+      cat "$1/template"
+    else
+      if [[ "$1" = "${SD_ROOT:-$HOME/sd}" ]]; then
+        cat <<EOF
+#!/usr/bin/env bash
+
+set -euo pipefail
+EOF
+      else
+        __sd_print_template "$(dirname "$1")"
+      fi
+    fi
+}
+
 __sd_new() {
-    local target="$1"
+    local script dir target body
+    target="$1"
     shift
 
     local -a command_path=()
@@ -127,9 +151,6 @@ __sd_new() {
     fi
 
     body="$*"
-    if [[ -n "$body" ]]; then
-        body=$(printf "\n%s" "$body")
-    fi
 
     script="$target"/"$(__sd_join_path "${command_path[@]}")"
 
@@ -138,108 +159,111 @@ __sd_new() {
         exit 1
     fi
 
-    mkdir -p "$(dirname "$script")"
-    cat > "$script" <<EOF
-#!/usr/bin/env bash
+    dir="$(dirname "$script")"
+    mkdir -p "$dir"
+    (
+      __sd_print_template "$dir"
+      if [[ -n "$body" ]]; then
+        printf "\n%s\n" "$body"
+      fi
+    ) >"$script"
+    
+    chmod +x "$script"
 
-set -euo pipefail
-$body
-EOF
-
-chmod +x "$script"
-
-if [[ -z "$body" ]]; then
-    __sd_edit "$script"
-fi
+    if [[ -z "$body" ]]; then
+        __sd_edit "$script"
+    fi
 }
 
-sman() (
-set -euo pipefail
+__sman() {
+    set -euo pipefail
 
-if [[ -n ${ZSH_EVAL_CONTEXT+x} ]]; then
-    # we need 0-indexed arrays so that the for loop
-    # in __sd_directory_help works properly
-    set -o KSH_ARRAYS
-fi
+    local target=${SD_ROOT:-$HOME/sman}
+    local arg
 
-local target=${SD_ROOT:-$HOME/sman}
-local arg
+    while [[ $# -gt 0 ]]; do
+        arg="$1"
+        if [[ -d "$target/$arg" ]]; then
+            target="$target/$arg"
+            shift
+        elif [[ -f "$target/$arg" ]]; then
+            target="$target/$arg"
+            shift
+            break
+        else
+            break
+        fi
+    done
 
-while [[ $# -gt 0 ]]; do
-    arg="$1"
-    if [[ -d "$target/$arg" ]]; then
-        target="$target/$arg"
-        shift
-    elif [[ -f "$target/$arg" ]]; then
-        target="$target/$arg"
-        shift
-        break
-    else
-        break
-    fi
-done
+    local found_help="false"
+    local found_new="false"
+    local found_edit="false"
+    local found_cat="false"
+    local found_which="false"
+    local found_really="false"
 
-local found_help="false"
-local found_new="false"
-local found_edit="false"
-local found_cat="false"
-local found_which="false"
-local found_really="false"
-
-for arg in "$@"; do
-    case "$arg" in
-        --help) found_help=true ;;
-        --new) found_new=true ;;
-        --edit) found_edit=true ;;
-        --cat) found_cat=true ;;
-        --which) found_which=true ;;
-        --really) found_really=true ;;
-    esac
-done
-
-if [[ "$found_really" = "true" ]]; then
-    local -a preserved=()
     for arg in "$@"; do
         case "$arg" in
-            '--really') shift; break ;;
-            *) preserved+=("$arg"); shift ;;
+            --help) found_help=true ;;
+            --new) found_new=true ;;
+            --edit) found_edit=true ;;
+            --cat) found_cat=true ;;
+            --which) found_which=true ;;
+            --really) found_really=true ;;
         esac
     done
-    if [[ ${#preserved[@]} -gt 0 ]]; then
-        set -- "${preserved[@]}" "$@"
-    fi
-elif [[ "$found_help" = "true" ]]; then
-    __sd_help "$target"
-    exit 0
-elif [[ "$found_new" = "true" ]]; then
-    __sd_new "$target" "$@"
-    exit 0
-elif [[ "$found_edit" = "true" ]]; then
-    __sd_edit "$target"
-    exit 0
-elif [[ "$found_cat" = "true" ]]; then
-    __sd_cat "$target"
-    exit 0
-elif [[ "$found_which" = "true" ]]; then
-    __sd_which "$target"
-    exit 0
-fi
 
-if [[ -d "$target" ]]; then
-    __sd_directory_help "$target"
-    if [[ $# -gt 0 ]]; then
-        echo >&2
-        echo "$target/$(__sd_join_path "$@") not found" >&2
-        exit 1
+    if [[ "$found_really" = "true" ]]; then
+        local -a preserved=()
+        for arg in "$@"; do
+            case "$arg" in
+                '--really') shift; break ;;
+                *) preserved+=("$arg"); shift ;;
+            esac
+        done
+        if [[ ${#preserved[@]} -gt 0 ]]; then
+            set -- "${preserved[@]}" "$@"
+        fi
+    elif [[ "$found_help" = "true" ]]; then
+        __sd_help "$target"
+        exit 0
+    elif [[ "$found_new" = "true" ]]; then
+        __sd_new "$target" "$@"
+        exit 0
+    elif [[ "$found_edit" = "true" ]]; then
+        __sd_edit "$target"
+        exit 0
+    elif [[ "$found_cat" = "true" ]]; then
+        __sd_cat "$target"
+        exit 0
+    elif [[ "$found_which" = "true" ]]; then
+        __sd_which "$target"
+        exit 0
     fi
-elif [[ -x "$target" ]]; then
-    "$target" "$@"
-else
-    __sd_cat "$@"
-fi
+
+    if [[ -d "$target" ]]; then
+        __sd_directory_help "$target"
+        if [[ $# -gt 0 ]]; then
+            echo >&2
+            echo "$target/$(__sd_join_path "$@") not found" >&2
+            exit 1
+        fi
+    elif [[ -x "$target" ]]; then
+        SD="$(dirname "$target")" exec "$target" "$@"
+    else
+        __sd_cat "$@"
+    fi
+}
+
+# If you source this file and use function-mode sman, we want to
+# wrap the execution in a subshell so that set -e doesn't kill
+# the interactive shell, and so that we can exec the subshell
+# without destroying the interactive shell.
+sman() (
+  __sman "$@"
 )
 
-# If you source this file, it will define the function sd,
+# If you source this file, it will define the function sman,
 # which you can use from your shell. If you *run* this file
 # as an executable, it will just invoke that function. We
 # have to do some tricks to detect that reliably on bash/zsh.
@@ -247,11 +271,11 @@ fi
 if [[ -n ${ZSH_EVAL_CONTEXT+x} ]]; then
     # we are in zsh
     if [[ "$ZSH_EVAL_CONTEXT" = toplevel ]]; then
-        sman "$@"
+        __sman "$@"
     fi
 elif [[ -n ${BASH_SOURCE[0]+x} ]]; then
     # we are in bash
     if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
-        sman "$@"
+        __sman "$@"
     fi
 fi
